### ISSUE TITLE
Sending a file using PLUS !

### ISSUE THREAD

**Issue by vanvantong** [mami-project/plus-lib#2]
Dear administrators of plus-lib,

I just want to ask that the plus-lib is complete or not because I saw some updates a few days ago.
Besides, could you show me how to run the experiment about sending a file using PLUS? 
I searched on the Internet and found nothing.

Thank you in advance!

**Comment by FMNSSun** [comment]
Hi,

What exactly is your interest in PLUS? I might be better able to help if I knew what you're trying to use it for.

As I've mentioned in the other issue the API is stable but since this is still a running project it may be subject to new additions but new additions won't interfere with existing usage of the API so this should be of no concern for people using plus-lib even though there is not yet an 'official' stable release. 

PLUS is NOT a transport protocol per se. It's more a protocol that sits between the IP-Layer and the transport layer and as such it can't be used independentely to transfer files. PLUS is for communicating with intermediate nodes on the path and provides this functionality to the layer above it. Thus, you need another protocol using/supporting PLUS which currently none really exist except our fork (see mami-project/plus-quic-go) of QUIC.

That said you certainly can transfer data through raw PLUS packets but PLUS since it is not a transport protocol does not have retransmissions or in-order guarantees. If you're trying to do that then reading the new HOWTO.md (in the project root) is a good start.

**Comment by vanvantong** [comment]
Hi FMNSSun,

As I read in some documents, I found that it is possible to require client add additional data into a stream using PLUS. I also found the description about PLUS header in your GitHub: https://mami-project.github.io/draft-trammell-plus-spec/.
I understand that PLUS will encapsulate old UDP packet with additional data and PLUS header. Is it right?
Where are the additional data inserted in the new packet? 
Besides, I want to add information from user side using PLUS. Could you show in detail how to do that?
Thank you in advance!

**Comment by FMNSSun** [comment]
If you are refering to the feedback mechanisms of PLUS then yes. If A wishes to communicate with the path A sends a packet with an extended header and sets PCF Type/Value/Len/Integrity to specify which information A wants from the path, the packet is sent and arrives at B while the nodes on the path will write the requested information into the header and B sends this back to A as feedback (otherwise A would never know what the path wrote into the header). However, PLUS sincd it's not a transport protocol does not specify where, when and how this data is sent back. PLUS only mandates that it must be sent back and that it must be encrypted. Feedback is sent back by the protocol using/supporting PLUS thus again... you need another protocol above PLUS. 

> Besides, I want to add information from user side using PLUS

What exactly do you mean by that?

**Comment by vanvantong** [comment]
I mean that I want to run the testbed about the way B responds with requested information to A. Could you show me how to do that?
As you said above, B will send the feedback when A requests. Can B send the information to A optionally without the requesting from A?
Besides, what is the encryption algorithm of PLUS?

**Comment by FMNSSun** [comment]
> Besides, what is the encryption algorithm of PLUS?

PLUS is **not** a transport protocol and it doesn't specify an encryption algorithm. The layer _above_ PLUS is responsible for encryption. 

> Can B send the information to A optionally without the requesting from A?

Not really. If a packet with an extended header arrives PLUS mandates that the layer above it sends the header back but it's not PLUS doing that. 

> I mean that I want to run the testbed about the way B responds with requested information to A. 

You can set the `ConnectionManager` into transparent mode using `SetTransparentMode` and then establish a connection and use the `QueuePCFRequest` method which will put it into the next outgoing packet (so you need to be sending data) and use the `GetFeedbackData` (or maybe it's called `GetPCFFeedbackData`) to get the feeback (you'll have to poll this). 

But this is more for testing.. in practice there should be a protocol above PLUS.

**Comment by shinichikudo987** [comment]
Thank you very much. I will follow your comment.

**Comment by vanvantong** [comment]
I read some drafts about PLUS, I found that there are 3 mechanisms: Sender-to-Path Declarations, Path-to-Receiver Declarations with Feedback, Direct Path-to-Sender Declarations.
I don't understand the purpose of  Sender-to-Path Declarations. Do you know the purpose of  Sender-to-Path Declarations?
When the client side (A) request information, the path will write the requested information into header and server side (B) will reply to client side (A) as feedback. Do you know where the path get the requested information?

**Comment by FMNSSun** [comment]
>  Sender-to-Path Declarations

You declare something to the path. You, as the sender, inform the path about something.

> Do you know where the path get the requested information?

The path just knows _somehow_. For example you could ask a node on the path what temperature it is (although that's of course not really a practical example) and the path will reply to that. How the path knows what it knows is completely out of scope. For most practical purposes information you request has to do with bandwidth/throughput, load on the path, maybe MTU and stuff like that related to network performance which the device knows through observation. You could for example request a hop count and each PLUS aware node on the path will increase the PCF value by one so at the end you know how many nodes there are on the path. 

It might help you to do some research about "Middle-box Cooperation Protocols" to better understand what PLUS is actually meant for.

**Comment by FMNSSun** [comment]
You should have a look at http://www.tik.ee.ethz.ch/file/13b641ddc2785efa50df126f4642fe96/PID5022959.pdf which describes what PLUS is about.

**Comment by vanvantong** [comment]
Thank you very much!
